### ISSUE TITLE
Wrong wiki link

### ISSUE THREAD

**Issue by penpineappleapplepen1** [dzaima/SOGL#3]
# Steps to reproduce the problem

1. Try to access the wiki page link from `readme.md`.
2. Observe the `404` error.

# Expected behavior

The wiki page link should work properly.

# What went wrong

It doesn't work. Instead a `404` error is displayed.

---

![](https://image.ibb.co/btdnCF/1.png)<br/>
![](https://image.ibb.co/jRkpRa/2.png)

**Comment by dzaima** [comment]
yep, that was linked to a folder of an old version with the file.

**Comment by dzaima** [comment]
[Fixed](https://github.com/dzaima/SOGL/commit/58afd64a8103cae2c63b5ed2870526fce0e2c05e).
